### ISSUE TITLE
On pod termination secret envars-* does not exist

### ISSUE THREAD

**Issue by ivankovnatsky** [danfromtitan/envars-from-node-labels#18]
We're using spot instances thus pods lifecycle is pretty lively with moving pods to new instances terminating them, etc. 

And recently we're started to see these kind of errors keeping our node off of termination gracefully:

```
secret envars-6659dc1b-d26c-413b-af17-c25ae946f4ec does not exist
```

Have you encountered something similar?

**Comment by danfromtitan** [comment]
I think the message is a red herring, it occurs because k8s API makes repeated attempts to delete a POD while the POD is in terminating status. While those attempts come through the webhook, the secret delete function gets called. First time it happens the secret gets deleted, subsecvent calls result in that message you've seen. 

To troubleshoo you'd enable verboseLogs in the controller - this will show all requests from k8s API and enable you to correlate with the controller logs. Please keep in mind the k8s API messages are asynchronius, so it takes a little while to dig through the pile. That would eventually help you to determine whether the problem you have is caused by the webhook or somewhere else.

**Comment by ivankovnatsky** [comment]
Not seeing this anymore.
